### ISSUE TITLE
import failed in python3, undefined symbol.

### ISSUE THREAD

**Issue by kiss187** [ImageMagick/PythonMagick#14]
imagemagick version: 7.0.7-11
python version: 3.5.2
pythonmagick version: 0.9.18

I build ImageMagick from github, there is no error in build log.
the print of `convert --version`
> Version: ImageMagick 7.0.7-11 Q8 x86_64 2017-11-27 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): fontconfig freetype jbig jng jp2 jpeg lzma pangocairo png tiff webp x zlib

and build PythonMagick as following steps:
- `./configure --with-python-min-version=3.5`
- sudo make && sudo make install

when I `import PythonMagick` in `python3` interpreter, there is an **error**
> Traceback (most recent call last):
  File "/home/whh/project/mihui_img_server/pg.py", line 4, in <module>
    import PythonMagick
  File "/usr/local/lib/python3.5/site-packages/PythonMagick/__init__.py", line 1, in <module>
    from . import _PythonMagick
ImportError: /usr/local/lib/python3.5/site-packages/PythonMagick/_PythonMagick.so: undefined symbol: _Z30Export_pyste_src_DrawableMattev

appreciation for any help. thanks.

**Comment by djorlando24** [comment]
Whoops, I just opened a new issue on what I think is the same problem. I thought my issue was OS-specific, perhaps not. I have a solution - check the suggested diffs.
